memodir = "$HOME/memo"
editor = "nvim"
column = 20
width = 0
selectcmd = "fzf"
grepcmd = "rg --line-number --no-heading --smart-case ${PATTERN} ${FILES}"
memotemplate = "$HOME/.config/memo/templates/md.txt"
assetsdir = "$HOME/memo"
pluginsdir = "$HOME/.config/memo/plugins"
templatedirfile = ""
templatebodyfile = ""
