[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#6b7089"
blue = "#91acd1"
cyan = "#95c4ce"
green = "#c0ca8e"
magenta = "#ada0d3"
red = "#e98989"
white = "#d2d4de"
yellow = "#e9b189"

[colors.normal]
black = "#161821"
blue = "#84a0c6"
cyan = "#89b8c2"
green = "#b4be82"
magenta = "#a093c7"
red = "#e27878"
white = "#c6c8d1"
yellow = "#e2a478"

[colors.primary]
background = "#161821"
foreground = "#d2d4de"

[env]
TERM = "xterm-256color"

[font]
size = 13.0

[font.bold]
family = "HackGen35 Console NF"
style = "Bold"

[font.bold_italic]
family = "HackGen35 Console NF"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 1

[font.italic]
family = "HackGen35 Console NF"
style = "Italic"

[font.normal]
family = "HackGen35 Console NF"
style = "Regular"

[font.offset]
x = 1
y = 2

[window]
decorations = "buttonless"
dynamic_padding = true
opacity = 0.9

[window.padding]
x = 8
y = 16
