name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE: ghrc.io/${{ github.repository_owner }}/dotfiles

    steps:
      - uses: actions/checkout@v2

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE }}:${{ github.sha }}

      - uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE }}:laetst
        if: github.ref == 'refs/heads/master'
